name: Create OCI Instance
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Write private key file
        env:
          OCI_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          echo "$OCI_PRIVATE_KEY" | base64 -d > /tmp/oci_private_key.pem
          chmod 600 /tmp/oci_private_key.pem
      - name: Run
        run: php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: /tmp/oci_private_key.pem
          OCI_AVAILABILITY_DOMAIN: ${{ vars.OCI_AVAILABILITY_DOMAIN }}
          OCI_SUBNET_ID: ${{ vars.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ vars.OCI_IMAGE_ID }}
          OCI_OCPUS: ${{ vars.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ vars.OCI_MEMORY_IN_GBS }}
          OCI_SHAPE: ${{ vars.OCI_SHAPE }}
          OCI_MAX_INSTANCES: ${{ secrets.OCI_MAX_INSTANCES }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
